language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-20.0.0
    - extra-android-support
    - extra-android-m2repository
    - android-20

script: "./gradlew build --stacktrace"
